### PR TITLE
delete listener immediately

### PR DESCRIPTION
**Pull request by jrwren**
Do not wait for GC to clean up UDP listener.

### CODE REVIEW

**Comment by jrwren** [comment]
This fixes issue https://github.com/ludia/pyramid_metrics/issues/1

**Comment by hadrien** [comment]
@jrwren: Just caught that, sorry for the delay: Thanks a lot for contributing!

@pior Is the reason to use 1 statsd client per request (rather than 1 per application) to avoid locking/waiting on statsd client's socket when a thread write on it?

**Comment by hadrien** [comment]
@pior @jrwren Would closing explicitly the statsd client' socket be safer?

```diff
diff --git a/pyramid_metrics/utility.py b/pyramid_metrics/utility.py
index 9016577..c9735dc 100644
--- a/pyramid_metrics/utility.py
+++ b/pyramid_metrics/utility.py
@@ -26,7 +26,8 @@ class MetricsUtilityUnavailable(MetricsError):
     pass


-def del_statsd(request):
+def finished_callback(request):
+    request.metrics._close()
     del request.metrics


@@ -46,7 +47,7 @@ def get_request_method(request):
     route_name = get_route_name(request)

     # Close the listening socket immediately at end of request.
-    request.add_finished_callback(del_statsd)
+    request.add_finished_callback(finished_callback)
     return MetricsUtility(statsd=statsd, route_name=route_name)


@@ -92,6 +93,9 @@ class MetricsUtility(object):
         else:
             return str(stat)

+    def _close(self):
+        self._statsd._sock.close()
+
     def incr(self, stat, count=1, per_route=False):
         """ Push a COUNTER metric """
         self._statsd.incr(self._key(stat), count=count)

```

**Comment by pior** [comment]
@hadrien There is no better reason than just KISS and see...

`MetricsUtility` has an internal state. 
But `StatsClient` is supposedly thread-safe and could be instantiated once. (no internal state, just plain `socket.sendto()`)

https://github.com/jsocol/pystatsd/blob/master/statsd/client.py#L145-L151

**Comment by hadrien** [comment]
@pior AFAIK `socket.send` is not thread safe, am I wrong? 
Anyway, I believe closing socket explicitly as I commented is the way to go.

**Comment by pior** [comment]
@hadrien This is using `sendto` not `send`. We are in [*connectionless UDP* ](http://www.cs.unc.edu/~dewan/242/s06/notes/sockets/node5.html)

And this is why I'm a bit surprised there is even anything to cleanup.

@jrwren We used `pyramid_metrics` on services with low traffic *per process*. Are you in a very different situation?

**Comment by pior** [comment]
Also, @jrwren were you able to confirm this is fixing the issue in your environment?

**Comment by jrwren** [comment]
Yes, this has been running in production since March 22nd

**Comment by pior** [comment]
The CI failure is unrelated (in coverage package / on 3.2 only).

**Comment by pior** [comment]
Merging this PR since it seems unlikely to bring any regressions

**Pull request merged**
